before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"
  - jruby-19mode # JRuby in 1.9 mode
