before_install:
  - sudo apt-get update -qq
  - uname -a

install:  
  # mecab
  - wget http://mecab.googlecode.com/files/mecab-0.996.tar.gz && tar xf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
  - sudo ldconfig
  # mecab-ipadic
  - wget http://mecab.googlecode.com/files/mecab-ipadic-2.7.0-20070801.tar.gz && tar xf mecab-ipadic-2.7.0-20070801.tar.gz
  - pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig
  - bundle install ffi
  
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"
  - jruby-19mode # JRuby in 1.9 mode
